[profile.default]
optimizer_runs = 1000000
verbosity = 1

[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
goerli = "${RPC_URL_GOERLI}"
arbitrum = "${RPC_URL_ARBITRUM}"

[etherscan]
sepolia = {key = "${ETHERSCAN_KEY}", url = "https://api-sepolia.etherscan.io/api"}
arbitrum = {key = "${ARBISCAN_KEY}"}
